Import('env', 'arch', 'cereal', 'messaging', 'common', 'gpucommon', 'visionipc')

libs = ['m', 'pthread', common, 'jpeg', 'OpenCL', 'yuv', cereal, messaging, 'zmq', 'capnp', 'kj', visionipc, gpucommon, 'atomic']

libs += ['opencv_core', 'opencv_highgui', 'opencv_imgproc', 'opencv_videoio']
env.Append(CXXFLAGS = '-DWEBCAM')
env.Append(CFLAGS = '-DWEBCAM')
env.Append(CPPPATH = ['/usr/include/opencv4', '/usr/local/include/opencv4'])

camera_obj = env.Object(['cameras/camera_webcam.cc', 'cameras/camera_common.cc', 'cameras/camera_util.cc'])
env.Program('camerad', [
    'main.cc',
    camera_obj,
  ], LIBS=libs)

if GetOption("test") and arch == "x86_64":
  env.Program('test/ae_gray_test',
              ['test/ae_gray_test.cc', camera_obj],
              LIBS=libs)